In [9]:
import tweepy
import webbrowser
import time
import pandas as pd

In [2]:
consumer_key = "SRKYbF44wb7ImB9c3XxppcX22"
consumer_secret = "GUZpAdVN31FRnD5Tjaxqk5l4tvMlQq6pGl01H7ThhwzVr6yRlV"

In [3]:
callback_uri = "oob"

In [4]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret, callback_uri)
request_url = auth.get_authorization_url()
webbrowser.open(request_url)
user_pin_input = input("What is the user pin? ")
auth.get_access_token(user_pin_input)

What is the user pin? 0160921

('933606174812983296-9GM7280599Gt9s0lmrCAXuwGLkyvo4h',
 'fnGPtm4epsfRBv3wJS6kSlNYC90P0Ijh80Zqzwr0I4MgA')

In [5]:
api = tweepy.API(auth)

In [6]:
my_timeline = api.home_timeline()

In [37]:
columns = set()
allowed_types = [str, int]
tweets_data = []
for status in my_timeline:
    status_dict = dict(vars(status))
    keys = status_dict.keys()
    single_tweet_data = {'user': status.user.screen_name, 'author': status.author.screen_name}
    for k in keys: 
        try:
            v_type = type(status_dict[k])
        except:
            v_type = None
        if v_type != None:
            if v_type in allowed_types:
                columns.add(k)
                single_tweet_data[k] = status_dict[k]
    tweets_data.append(single_tweet_data)
            
header_cols = list(columns)
header_cols.append('user')
header_cols.append('author')

In [24]:
df = pd.DataFrame(tweets_data, columns=header_cols)
df.head()

,source,retweet_count,quoted_status_id_str,quoted_status_id,id,source_url,text,id_str,lang,favorite_count,user,author
0,friendly fem tech bot,3,NaN,NaN,1334144041445945344,https://rike.dev,RT @jucktion: Responsive Website Using The Pri...,1334144041445945344,en,0,femtech_,femtech_
1,friendly fem tech bot,6,NaN,NaN,1334143774193283074,https://rike.dev,RT @adahagan: I'm super excited to FINALLY hav...,1334143774193283074,en,0,femtech_,femtech_
2,friendly fem tech bot,3,NaN,NaN,1334143772922433540,https://rike.dev,RT @Tertill_Corp: Congrats @helengreiner Terti...,1334143772922433540,en,0,femtech_,femtech_
3,Twitter Web App,0,NaN,NaN,1334143746460561413,https://mobile.twitter.com,Banks put on the spot for mimicking ‘rogue’ di...,1334143746460561413,en,1,citizentvkenya,citizentvkenya
4,friendly fem tech bot,1,NaN,NaN,1334143663199416325,https://rike.dev,RT @The_Jo_Knows: Five Jobs In Tech For Women ...,1334143663199416325,en,0,femtech_,femtech_

In [34]:
def extract_timeline_as_df(timeline_list):
    columns = set()
    allowed_types = [str, int]
    tweets_data = []
    for status in timeline_list:
        status_dict = dict(vars(status))
        keys = status_dict.keys()
        single_tweet_data = {'user': status.user.screen_name, 'author': status.author.screen_name}
        for k in keys: 
            try:
                v_type = type(status_dict[k])
            except:
                v_type = None
            if v_type != None:
                if v_type in allowed_types:
                    columns.add(k)
                    single_tweet_data[k] = status_dict[k]
        tweets_data.append(single_tweet_data)

    header_cols = list(columns)
    header_cols.append('user')
    header_cols.append('author')
    df = pd.DataFrame(tweets_data, columns=header_cols)
    return df

In [38]:
user = api.get_user('code') 
user_timeline = user.timeline()

In [35]:
df2 = extract_timeline_as_df(user_timeline)
df2.head()

,source,retweet_count,in_reply_to_status_id,quoted_status_id_str,in_reply_to_user_id_str,quoted_status_id,in_reply_to_status_id_str,id,source_url,text,id_str,in_reply_to_screen_name,lang,favorite_count,in_reply_to_user_id,user,author
0,Buffer,31,NaN,NaN,NaN,NaN,NaN,1333852878314803201,https://buffer.com,Are you using WSL? Do you SSH into VMs or use ...,1333852878314803201,NaN,en,182,NaN,code,code
1,Buffer,13,NaN,NaN,NaN,NaN,NaN,1333815626238980097,https://buffer.com,RT @mattbierner: Today's @code tip: managing m...,1333815626238980097,NaN,en,0,NaN,code,code
2,Buffer,18,NaN,NaN,NaN,NaN,NaN,1333546605606293506,https://buffer.com,RT @mattbierner: The latest @code 0 to 20 prov...,1333546605606293506,NaN,en,0,NaN,code,code
3,TweetDeck,26,NaN,NaN,NaN,NaN,NaN,1333540692711370754,https://about.twitter.com/products/tweetdeck,RT @jimbobbennett: Did you know you can run @c...,1333540692711370754,NaN,en,0,NaN,code,code
4,Buffer,4,NaN,1333475002335674368,NaN,1.333475e+18,NaN,1333490985200914432,https://buffer.com,Claudia Regio on Twitter https://t.co/WxY4m6Gie5,1333490985200914432,NaN,en,42,NaN,code,code

In [36]:
%%writefile users_timeline.py

import tweepy
import webbrowser
import time
import pandas as pd

consumer_key = "SRKYbF44wb7ImB9c3XxppcX22"
consumer_secret = "GUZpAdVN31FRnD5Tjaxqk5l4tvMlQq6pGl01H7ThhwzVr6yRlV"
callback_uri = "oob"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret, callback_uri)
request_url = auth.get_authorization_url()
webbrowser.open(request_url)
user_pin_input = input("What is the user pin? ")
auth.get_access_token(user_pin_input)

api = tweepy.API(auth)

def extract_timeline_as_df(timeline_list):
    columns = set()
    allowed_types = [str, int]
    tweets_data = []
    for status in timeline_list:
        status_dict = dict(vars(status))
        keys = status_dict.keys()
        single_tweet_data = {'user': status.user.screen_name, 'author': status.author.screen_name}
        for k in keys: 
            try:
                v_type = type(status_dict[k])
            except:
                v_type = None
            if v_type != None:
                if v_type in allowed_types:
                    columns.add(k)
                    single_tweet_data[k] = status_dict[k]
        tweets_data.append(single_tweet_data)

    header_cols = list(columns)
    header_cols.append('user')
    header_cols.append('author')
    df = pd.DataFrame(tweets_data, columns=header_cols)
    return df

user = api.get_user('code') 
user_timeline = user.timeline()
df2 = extract_timeline_as_df(user_timeline)
df2.head()

Writing users_timeline.py